### ISSUE TITLE
Práctica 1 Realidad Aumentada y Realidad Virtual

### ISSUE THREAD

**Issue by Freddy50309** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-Freddy50309#2]
Se da a conocer el análisis de algunas aplicaciones que involucran Realidad aumentada y Realidad Virtual y tener una mejor comprensión de estos temas
[Practica.1.docx.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-Freddy50309/files/6138014/Practica.1.docx.pdf)

**Comment by ArteezyOne** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
